language: go
services: postgres

go:
    - 1.5
    - tip

before_script:
    - psql -c 'create database upchecker_test;' -U postgres
    - >-
        cat << EOF > database-config.json
         {
           "address": "localhost:5432",
           "user": "postgres",
           "password": "",
           "ssl": false,
           "database": "upchecker_test"
         }

matrix:
    allow_failures:
        - go: tip

